version: "3.8"
services:

  server:
    build: .
    container_name: node_server
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    command: npm start
  
  # mongo:
  #   image: mongo
  #   ports:
  #     - '27017:27017'